### ISSUE TITLE
The plugin no longer works

### ISSUE THREAD

**Issue by JulesNdanga** [Jack-Dane/odoo-wp-plugin#16]
**Describe the bug**
I no longer receive leads on odoo and I have no errors.

**Platform versions:**

-Odoo Version: Odoo saas~16.3+e (Edition Enterprise)
Odoo Platform Odoo online
WP Version: 6.2.2
PHP Version: 8.2
Contact Form 7 Version: 5.7.7
Contact 7 to Odoo connector : 0.0.2

**Comment by Jack-Dane** [comment]
Hi @JulesNdanga, 

It is unlikely that the plugin broke without any code changes if it has been working fine, did you upgrade to 0.0.1 from 0.0.2 and it started to break? 

Maybe something else was upgraded to make it break? 

My first guess would be that maybe an Odoo field was deleted that the plugin was using or credentials were changed for the user accessing the Odoo.

**Comment by JulesNdanga** [comment]
Hello @Jack-Dane 
I updated the plugin to latest version 0.0.3. The connection test to odoo works well, but the prospect reception is still not happening. I checked if all the fields are present and they are. Here is the capture of the mapping of the different fields.
![image](https://github.com/Jack-Dane/odoo-wp-plugin/assets/39867668/4602c02b-0af2-491e-ba92-b136ae95b76a)

**Comment by JulesNdanga** [comment]
The problem was the many2one field, which I added.

**Comment by JulesNdanga** [comment]
Is there a way to concatenate two fields when sending to odoo?

**Comment by Jack-Dane** [comment]
@JulesNdangam Unfortunately I haven't completed the feature to support many2one fields, but that will be in version 0.0.4 as my next thing to do. 

For concatenating fields, the ticket is still open, but this can easily be achieved using either a [computed field](https://www.odoo.com/documentation/16.0/developer/tutorials/getting_started/09_compute_onchange.html#computed-fields) (I think you can use Studio for this) or an [automated action[(https://www.odoo.com/documentation/16.0/applications/productivity/studio/automated_actions.html#automated-actions-automations) that concatenates the two fields the form submits to, into a new field on creation.

**Comment by JulesNdanga** [comment]
Thanks @Jack-Dane  for your help, I'll try that.
