### ISSUE TITLE
Use consistent table display

### ISSUE THREAD

**Issue by Jack-Dane** [Jack-Dane/odoo-wp-plugin#18]
As a developer,  

I would like to have a display table that isn't maintained by the plugin, 

Because it is difficult to maintain for all browsers + operating systems. 

* It should provide a more stable plugin across multiple browsers + operating systems. 
* I believe the custom JS is causing issues in this ticket #17 
* I have seen a common table display being used across plugins, but I couldn't see any documentation on how to use it. Eg: 

![Capture](https://github.com/Jack-Dane/odoo-wp-plugin/assets/17383921/1870420d-bda6-440b-8ec6-ae7006150170)

**Comment by JulesNdanga** [comment]
You also need to make sure that you install all the dependencies, this can also pose a problem. Since I don't encounter this problem on my side. For this problem, can reinstall the plugin to see if it happens again.
