### ISSUE TITLE
500 (Internal Server Error) on Odoo Connections

### ISSUE THREAD

**Issue by Muntasir-Mahmud** [Jack-Dane/odoo-wp-plugin#21]
I am getting 500 (Internal Server Error) on Submit of Odoo Connections. I have changed the browser but it didn't work. @Jack-Dane please help.
![image](https://github.com/Jack-Dane/odoo-wp-plugin/assets/47689933/97a296e4-952f-461c-b9b2-d0799af041f5)

**Comment by Jack-Dane** [comment]
Hi @Muntasir-Mahmud, 

A 500 error would suggest something has gone wrong on the WordPress server side, do you have any error logs from WordPress you could supply to help debug the issue?

**Comment by Muntasir-Mahmud** [comment]
@Jack-Dane Thanks you for your comment. Apparently, this error was occurring in local environment. From the server everything is okey. I have a question though, How can I send many2many field constant value? Like I want to send specific tags from the wordpress.

**Comment by Jack-Dane** [comment]
@Muntasir-Mahmud, unfortunately adding Many2Many or One2Many fields on submit isn't supported. 

A suggested workaround would be to create an automated action to add them on some condition that could only be present when submitting from the WordPress site.

**Comment by Muntasir-Mahmud** [comment]
@Jack-Dane Can you please tell me how can I add the automated action?

**Comment by Muntasir-Mahmud** [comment]
Hello @Jack-Dane . I had to test some thing in local computer. On Submit of Odoo Connections I am getting 500 error message again.  Here is the image of log
![image](https://github.com/Jack-Dane/odoo-wp-plugin/assets/47689933/0cccf5dc-528c-492f-a4e6-b9a82b377663)

**Comment by Jack-Dane** [comment]
@Muntasir-Mahmud, sorry for the delay, it looks like `fopen` is returning `false` when creating the encryption file.  

And the error log suggests WordPress doesn't have the correct permissions to write to `/opt/lampp/htdocs/wordpress/`. The `/opt` directory is usually owned by root, I wouldn't expect this in a standard install of WordPress. 

Maybe you change the owner of the WordPress directory to the same as the owner of the WordPress service? I am not sure how WordPress is configured on your machine to know who this user is.
