### ISSUE TITLE
the Plug in cant activate

### ISSUE THREAD

**Issue by Rloldan115** [Jack-Dane/odoo-wp-plugin#25]
Warning: require(vendor/autoload.php)

**Comment by Jack-Dane** [comment]
@Rloldan115, you will have to give me a bit more information. How did you download and install the plugin in your WordPress site? 

If you downloaded the source code, did you install the requirements with composer first before installing?

**Comment by Rloldan115** [comment]
Hi, Dane apologize for the delayed reply, yes thanks for the instruction I've successfully installed the plug-in in our WordPress website we're currently using the latest version of WP and CF7 and the Odoo version is Odoo16 enterprise. Maybe I'm just figuring out how to map it on the field that is One to Many and Many to Many, I encountered a problem in this specific Field Function, It won't transmit data, when I map a function on there but the rest seems to look fine.

**Comment by Jack-Dane** [comment]
@Rloldan115, no problem, glad to hear you have it working. I will close this ticket since it is working for you. 

> figuring out how to map it on the field that is One to Many and Many to Many

Currently, these field types aren't supported, there is a feature I will be working on to implement them.
