### ISSUE TITLE
Prospects are not sent to CRM

### ISSUE THREAD

**Issue by JulesNdanga** [Jack-Dane/odoo-wp-plugin#7]
The information filled in the contact form 7 form does not arrive in odoo. Unlike your example in the video, I use the crm.lead model to automatically create pipelines. And no error is returned when I do the tests.

**Comment by JulesNdanga** [comment]
Some fields have also been done with studio in odoo

**Comment by Jack-Dane** [comment]
@JulesNdanga, thanks again for the issue. 

Could you let me know the Odoo version that you are using? 

I have tested locally on Odoo 16 which worked fine at creating an opportunity, a few things to make sure you have done: 

- Added a `type` field that is being sent to Odoo as it is a required field. 
- Don't add a forward slash at the end of the URL for the connection instant. 

Could you also share the Odoo logs as well, you should see something like this: 
```
odoo-web-1  | 2023-07-05 19:54:23,755 1 INFO Test odoo.addons.base.models.res_users: Login successful for db:<db name> login:<email> from n/a 
odoo-web-1  | 2023-07-05 19:54:23,755 1 INFO Test werkzeug: 172.18.0.1 - - [05/Jul/2023 19:54:23] "POST /xmlrpc/2/common HTTP/1.0" 200 - 8 0.004 0.285
odoo-web-1  | 2023-07-05 19:54:23,805 1 INFO Test werkzeug: 172.18.0.1 - - [05/Jul/2023 19:54:23] "POST /xmlrpc/2/object HTTP/1.0" 200 - 30 0.014 0.035
```

**Comment by JulesNdanga** [comment]
Hello Dan. I use Odoo saas~16.2+e (Enterprise Edition), I did not put the trailing slash at the url level and I will make sure that the type of fields correspond to those of the model in odoo and I come back to you on that.

**Comment by JulesNdanga** [comment]
In the example of the video for the link of your server it is in http, I put https, given the ssl security certificate is active, can this be a problem?

**Comment by Jack-Dane** [comment]
Thanks for supplying the Odoo version. 

Sending data using SSL encryption shouldn't be an issue, I have used the same API for a secure connection before and it was ok but I will see if I can try again later. 

Are you able to check the Odoo logs?

It might also help if you can send screen shots of the field mapping table and the CF7 form code you are trying to use.

**Comment by JulesNdanga** [comment]
![image](https://github.com/Jack-Dane/odoo-wp-plugin/assets/39867668/b67ad345-a005-4e04-ac1f-3913c51e8b5b)
![image](https://github.com/Jack-Dane/odoo-wp-plugin/assets/39867668/de26acd0-e8c6-459f-a2fb-afea9068d6da)

**Comment by JulesNdanga** [comment]
Here are the screenshots of CF7 form field mapping table and code. Here are the screenshots of the CF7 form field mapping table and code. Since odoo cloud, I don't have access to the log file.

**Comment by JulesNdanga** [comment]
But did you also have to test with the "crm.lead" to automatically create an opportunity?

**Comment by JulesNdanga** [comment]
It's good, it's the studio fields that prevent this.
![image](https://github.com/Jack-Dane/odoo-wp-plugin/assets/39867668/1e1d7be1-e6ab-4d8f-b945-d7f634cbe7e0)
I suggest you some features to implement.
-Popup info that returns the error that occurred to make it easier to solve the problem.
-Integration of other form plugins (ninja...etc) and also support for forms made with elementor or divi
- Support for fields generated by studio (perhaps it would be necessary to make an example video to specify that this is not supported and also for the required fields, perhaps to make a detailed doc).
That's about all.
Thanks again for your plugin. You should put it on wordpress and maybe make a free premium version with some paid features.

**Comment by Jack-Dane** [comment]
Glad you have it working and thanks for your feedback @JulesNdanga. 

I agree, the error reporting could be improved so I have created a story for that: https://github.com/Jack-Dane/odoo-wp-plugin/issues/8

Further integration is planned, but a solid foundation with CF7 is required first (eg: ironing out these issues you have noted). 

I wasn't aware of the unsupported studio fields, unfortunately, I don't have access to an instance with studio to test why it didn't work. I will make an effort to note this in the README.md so others are aware. When implementing similar API requests, I don't recall having a problem entering data into studio fields. But this was with Odoo.sh, maybe there is a difference with Odoo online.
